import { ArrowRightOnRectangleIcon } from "@heroicons/react/24/outline";
import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import img from "../../public/landing-page-bg.png";

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="fixed -z-10 h-screen w-screen  animate-saturation overflow-hidden">
      <Image src={img} alt="Mountains" layout="fill" objectFit="cover" quality={50} />
    </div>

    <div className="hero h-full">
      <div className="hero-content w-fit rounded-lg bg-black/50 p-8 text-center text-white">
        <div>
          <h1 className="text-lg font-bold sm:text-2xl md:text-3xl lg:text-4xl">
            Salen
            <br />
            samfällighetsförening
          </h1>
          <p className="py-8">Tomtebo, Umeå</p>
          <Link href="/auth/signin">
            <a className="btn btn-primary w-full md:w-2/4">
              <div className="flex flex-row items-center gap-2">
                <ArrowRightOnRectangleIcon className="h-6 w-6" />
                Logga in
              </div>
            </a>
          </Link>
        </div>
      </div>
    </div>
  </>
);

export default Home;
